Fix wbec update script on wb85 (#56)

diff --git a/tools/wb-ec-firmware-update b/tools/wb-ec-firmware-update
--- a/tools/wb-ec-firmware-update
+++ b/tools/wb-ec-firmware-update
@@ -47,8 +47,6 @@ DT_OVERLAY="
 /dts-v1/;
 /plugin/;
 / {
-    compatible = \"wirenboard,wirenboard-740\";
-
     fragment-wbec-disable {
         target = <&wbec>;
         __overlay__ {
@@ -85,8 +83,7 @@ remove_overlay_and_start_drivers() {
     # where we can't manage services and kernel modules,
     # so this check will suppress error messages.
     if [[ -x "$(which ischroot)" ]] && ! ischroot; then
-        modprobe pwrkey-wbec
-
+        systemctl restart wb-mqtt-serial
         systemctl restart wb-mqtt-gpio
         systemctl restart wb-mqtt-adc
         systemctl restart wb-rules
@@ -120,10 +117,7 @@ GPIO_BOOT0_NUM=$(gpiofind "$GPIO_BOOT0") || {
 # where we can't manage services and kernel modules,
 # so this check will suppress error messages.
 if [[ -x "$(which ischroot)" ]] && ! ischroot; then
-    # Remove pwrkey driver
-    modprobe -r pwrkey-wbec
-
-    # Stop services
+    systemctl stop wb-mqtt-serial
     systemctl stop wb-mqtt-gpio
     systemctl stop wb-mqtt-adc
     systemctl stop wb-rules
@@ -143,6 +137,10 @@ for FIRMWARE in $FIRMWARES_ORDER; do
         exit -1
     fi
 
+    # Kill processes that use wbec-uart ports
+    if [[ -x "$(which fuser)" ]]; then
+        fuser -k -TERM /dev/ttyWBE* || true
+    fi
     # Apply overlay to disable spi and enable i2c
     remove_overlay
     mkdir $DT_OVERLAY_DIR
@@ -204,3 +202,6 @@ for FIRMWARE in $FIRMWARES_ORDER; do
         break
     fi
 done
+
+echo
+echo "Reboot is required after Embedded Controller firmware update"
